import type { ImagePlaceholder } from './placeholder-images';
import { getImage } from './images';

export type Product = {
  id: string;
  name: string;
  category: 'grains' | 'supplements' | 'juices' | 'nuts' | 'oils' | 'flours';
  description: string;
  price: number;
  unit: 'kg' | 'g' | 'un' | 'ml' | 'l';
  image: ImagePlaceholder;
};

export const products: Product[] = [
  // Grãos e Sementes
  {
    id: 'quinoa',
    name: 'Quinoa Orgânica',
    category: 'grains',
    description: 'Grãos de quinoa orgânica, ricos em proteínas e fibras. Perfeito para uma refeição saudável e completa.',
    price: 25.50,
    unit: 'g',
    image: getImage('quinoa-grain'),
  },
  {
    id: 'chia',
    name: 'Sementes de Chia',
    category: 'grains',
    description: 'Sementes de chia ricas em ômega-3, fibras e antioxidantes. Ideal para adicionar em iogurtes e smoothies.',
    price: 15.00,
    unit: 'g',
    image: getImage('chia-seeds'),
  },
  {
    id: 'oats',
    name: 'Aveia em Flocos',
    category: 'grains',
    description: 'Aveia orgânica em flocos, fonte de energia de liberação lenta e fibras solúveis.',
    price: 12.90,
    unit: 'g',
    image: getImage('oats'),
  },
  {
    id: 'linhaça-dourada',
    name: 'Linhaça Dourada',
    category: 'grains',
    description: 'Sementes de linhaça dourada, excelente fonte de fibras e ômega-3.',
    price: 8.50,
    unit: 'g',
    image: getImage('flax-seeds'),
  },
  {
    id: 'amaranto',
    name: 'Grão de Amaranto',
    category: 'grains',
    description: 'Grão de amaranto sem glúten, rico em proteínas e aminoácidos essenciais.',
    price: 18.75,
    unit: 'g',
    image: getImage('amaranth'),
  },
  {
    id: 'trigo-sarraceno',
    name: 'Trigo Sarraceno',
    category: 'grains',
    description: 'Trigo sarraceno orgânico, ideal para dietas sem glúten e rico em nutrientes.',
    price: 22.00,
    unit: 'g',
    image: getImage('buckwheat'),
  },

  // Suplementos
  {
    id: 'protein',
    name: 'Proteína Vegana',
    category: 'supplements',
    description: 'Mix de proteínas vegetais (ervilha, arroz e chia) para recuperação muscular e aporte proteico.',
    price: 99.90,
    unit: 'un',
    image: getImage('protein-powder'),
  },
  {
    id: 'vitamin-d',
    name: 'Vitamina D3',
    category: 'supplements',
    description: 'Cápsulas de Vitamina D3 para saúde óssea e fortalecimento do sistema imunológico.',
    price: 45.00,
    unit: 'un',
    image: getImage('vitamin-d'),
  },
  {
    id: 'omega-3',
    name: 'Ômega 3',
    category: 'supplements',
    description: 'Suplemento de ômega 3 de óleo de peixe, essencial para a saúde do cérebro e coração.',
    price: 65.00,
    unit: 'un',
    image: getImage('omega-3'),
  },
  {
    id: 'spirulina',
    name: 'Spirulina em Pó',
    category: 'supplements',
    description: 'Spirulina orgânica em pó, superalimento rico em proteínas, vitaminas e minerais.',
    price: 55.00,
    unit: 'g',
    image: getImage('spirulina'),
  },
  {
    id: 'colageno',
    name: 'Colágeno Hidrolisado',
    category: 'supplements',
    description: 'Colágeno hidrolisado para saúde da pele, cabelos e articulações.',
    price: 75.00,
    unit: 'g',
    image: getImage('collagen'),
  },
  {
    id: 'probiotico',
    name: 'Probiótico 30 Bilhões',
    category: 'supplements',
    description: 'Cápsulas de probiótico com 30 bilhões de UFC para saúde intestinal.',
    price: 89.90,
    unit: 'un',
    image: getImage('probiotic'),
  },

  // Sucos e Bebidas
  {
    id: 'green-juice',
    name: 'Suco Verde Detox',
    category: 'juices',
    description: 'Suco prensado a frio com couve, espinafre, maçã, pepino e limão. Revitalizante e nutritivo.',
    price: 18.00,
    unit: 'ml',
    image: getImage('green-juice'),
  },
  {
    id: 'berry-shake',
    name: 'Shake de Frutas Vermelhas',
    category: 'juices',
    description: 'Shake antioxidante com morango, mirtilo, amora e banana. Uma explosão de sabor e saúde.',
    price: 22.00,
    unit: 'ml',
    image: getImage('detox-shake'),
  },
  {
    id: 'energy-smoothie',
    name: 'Smoothie Energético',
    category: 'juices',
    description: 'Smoothie tropical com manga, abacaxi e maracujá. Perfeito para um boost de energia.',
    price: 20.00,
    unit: 'ml',
    image: getImage('energy-smoothie'),
  },
  {
    id: 'suco-laranja-cenoura',
    name: 'Suco de Laranja com Cenoura',
    category: 'juices',
    description: 'Suco natural de laranja com cenoura, rico em vitamina A e C.',
    price: 15.00,
    unit: 'ml',
    image: getImage('orange-carrot-juice'),
  },
  {
    id: 'shot-detox',
    name: 'Shot Detox de Gengibre',
    category: 'juices',
    description: 'Shot concentrado de gengibre e limão para imunidade e digestão.',
    price: 12.00,
    unit: 'ml',
    image: getImage('ginger-shot'),
  },
  {
    id: 'agua-coco',
    name: 'Água de Coco Natural',
    category: 'juices',
    description: 'Água de coco 100% natural, isotônico natural rico em eletrólitos.',
    price: 10.00,
    unit: 'ml',
    image: getImage('coconut-water'),
  },

  // Castanhas e Oleaginosas
  {
    id: 'castanha-para',
    name: 'Castanha do Pará',
    category: 'nuts',
    description: 'Castanha do Pará orgânica, uma das melhores fontes naturais de selênio.',
    price: 35.00,
    unit: 'g',
    image: getImage('brazil-nuts'),
  },
  {
    id: 'amendoas',
    name: 'Amêndoas Cruas',
    category: 'nuts',
    description: 'Amêndoas cruas e sem sal, ricas em vitamina E e gorduras boas.',
    price: 28.50,
    unit: 'g',
    image: getImage('almonds'),
  },
  {
    id: 'nozes',
    name: 'Nozes Pecan',
    category: 'nuts',
    description: 'Nozes pecan selecionadas, perfeitas para lanches e receitas.',
    price: 42.00,
    unit: 'g',
    image: getImage('pecan-nuts'),
  },
  {
    id: 'castanha-caju',
    name: 'Castanha de Caju',
    category: 'nuts',
    description: 'Castanha de caju torrada sem sal, fonte de zinco e magnésio.',
    price: 25.00,
    unit: 'g',
    image: getImage('cashew-nuts'),
  },

  // Óleos e Manteigas
  {
    id: 'azeite-extra-virgem',
    name: 'Azeite Extra Virgem',
    category: 'oils',
    description: 'Azeite extra virgem prensado a frio, ideal para saladas e finalizações.',
    price: 45.00,
    unit: 'ml',
    image: getImage('olive-oil'),
  },
  {
    id: 'oleo-coco',
    name: 'Óleo de Coco Extra Virgem',
    category: 'oils',
    description: 'Óleo de coco extra virgem orgânico, versátil para culinária e cuidados pessoais.',
    price: 38.00,
    unit: 'ml',
    image: getImage('coconut-oil'),
  },
  {
    id: 'manteiga-amendoim',
    name: 'Manteiga de Amendoim Natural',
    category: 'oils',
    description: 'Manteiga de amendoim 100% natural, sem açúcar ou conservantes.',
    price: 22.00,
    unit: 'g',
    image: getImage('peanut-butter'),
  },

  // Farinhas e Bases
  {
    id: 'farinha-amendoa',
    name: 'Farinha de Amêndoa',
    category: 'flours',
    description: 'Farinha de amêndoa fina, ideal para receitas low-carb e sem glúten.',
    price: 32.00,
    unit: 'g',
    image: getImage('almond-flour'),
  },
  {
    id: 'farinha-coco',
    name: 'Farinha de Coco',
    category: 'flours',
    description: 'Farinha de coco orgânica, rica em fibras e pobre em carboidratos.',
    price: 28.50,
    unit: 'g',
    image: getImage('coconut-flour'),
  },
  {
    id: 'farinha-aveia',
    name: 'Farinha de Aveia',
    category: 'flours',
    description: 'Farinha de aveia integral, perfeita para panquecas e bolos saudáveis.',
    price: 15.00,
    unit: 'g',
    image: getImage('oat-flour'),
  },
  // Grãos e Sementes (Adicionais - Total 16)
  {
    id: 'arroz-integral',
    name: 'Arroz Integral Orgânico',
    category: 'grains',
    description: 'Arroz integral de grão longo, rico em fibras e vitaminas do complexo B.',
    price: 10.90,
    unit: 'kg',
    image: getImage('brown-rice'),
  },
  {
    id: 'lentilha',
    name: 'Lentilha Canadense',
    category: 'grains',
    description: 'Lentilha de alta qualidade, excelente fonte de proteína vegetal e ferro.',
    price: 14.50,
    unit: 'kg',
    image: getImage('lentils'),
  },
  {
    id: 'grao-bico',
    name: 'Grão de Bico',
    category: 'grains',
    description: 'Grão de bico seco, ideal para hummus, saladas e pratos quentes.',
    price: 16.00,
    unit: 'kg',
    image: getImage('chickpeas'),
  },
  {
    id: 'feijao-preto',
    name: 'Feijão Preto Orgânico',
    category: 'grains',
    description: 'Feijão preto orgânico, essencial na culinária brasileira, rico em ferro.',
    price: 9.50,
    unit: 'kg',
    image: getImage('black-beans'),
  },
  {
    id: 'milho-pipoca',
    name: 'Milho para Pipoca Orgânico',
    category: 'grains',
    description: 'Milho para pipoca orgânico, sem agrotóxicos, para um lanche saudável.',
    price: 7.00,
    unit: 'kg',
    image: getImage('popcorn-corn'),
  },
  {
    id: 'cevada',
    name: 'Cevada em Grãos',
    category: 'grains',
    description: 'Cevada em grãos, excelente para sopas e saladas, fonte de betaglucanas.',
    price: 11.20,
    unit: 'kg',
    image: getImage('barley'),
  },
  {
    id: 'painco',
    name: 'Painço Descascado',
    category: 'grains',
    description: 'Painço descascado, grão sem glúten, versátil para diversas receitas.',
    price: 13.80,
    unit: 'g',
    image: getImage('millet'),
  },
  {
    id: 'gergelim',
    name: 'Gergelim Branco',
    category: 'grains',
    description: 'Sementes de gergelim branco, ricas em cálcio e magnésio.',
    price: 17.50,
    unit: 'g',
    image: getImage('sesame-seeds'),
  },
  {
    id: 'semente-girassol',
    name: 'Semente de Girassol',
    category: 'grains',
    description: 'Sementes de girassol cruas, ricas em vitamina E e gorduras saudáveis.',
    price: 19.00,
    unit: 'g',
    image: getImage('sunflower-seeds'),
  },
  {
    id: 'canjica',
    name: 'Canjica Branca',
    category: 'grains',
    description: 'Canjica branca, ideal para sobremesas e pratos típicos.',
    price: 6.50,
    unit: 'kg',
    image: getImage('hominy'),
  },

  // Suplementos (Adicionais - Total 16)
  {
    id: 'creatina',
    name: 'Creatina Monohidratada',
    category: 'supplements',
    description: 'Suplemento de creatina para aumento de força e performance muscular.',
    price: 85.00,
    unit: 'un',
    image: getImage('creatine'),
  },
  {
    id: 'bcaa',
    name: 'BCAA em Pó',
    category: 'supplements',
    description: 'Aminoácidos de cadeia ramificada para recuperação e construção muscular.',
    price: 79.90,
    unit: 'un',
    image: getImage('bcaa'),
  },
  {
    id: 'multivitaminico',
    name: 'Multivitamínico Completo',
    category: 'supplements',
    description: 'Suplemento com vitaminas e minerais essenciais para o dia a dia.',
    price: 55.00,
    unit: 'un',
    image: getImage('multivitamin'),
  },
  {
    id: 'magnesio',
    name: 'Cloreto de Magnésio P.A.',
    category: 'supplements',
    description: 'Magnésio para saúde óssea, muscular e do sistema nervoso.',
    price: 35.00,
    unit: 'un',
    image: getImage('magnesium-chloride'),
  },
  {
    id: 'curcuma',
    name: 'Cúrcuma em Cápsulas',
    category: 'supplements',
    description: 'Cápsulas de cúrcuma com pimenta preta para máxima absorção e ação anti-inflamatória.',
    price: 49.90,
    unit: 'un',
    image: getImage('turmeric-capsules'),
  },
  {
    id: 'psyllium',
    name: 'Psyllium em Pó',
    category: 'supplements',
    description: 'Fibra solúvel natural para saúde intestinal e controle de apetite.',
    price: 29.00,
    unit: 'g',
    image: getImage('psyllium'),
  },
  {
    id: 'maca-peruana',
    name: 'Maca Peruana em Pó',
    category: 'supplements',
    description: 'Maca peruana para energia, vitalidade e equilíbrio hormonal.',
    price: 42.00,
    unit: 'g',
    image: getImage('maca-powder'),
  },
  {
    id: 'oleo-cartamo',
    name: 'Óleo de Cártamo em Cápsulas',
    category: 'supplements',
    description: 'Óleo de cártamo para auxílio na queima de gordura e definição muscular.',
    price: 59.00,
    unit: 'un',
    image: getImage('safflower-oil-capsules'),
  },
  {
    id: 'glucosamina',
    name: 'Glucosamina e Condroitina',
    category: 'supplements',
    description: 'Suplemento para saúde das articulações e cartilagens.',
    price: 68.00,
    unit: 'un',
    image: getImage('glucosamine-chondroitin'),
  },
  {
    id: 'vitamina-c',
    name: 'Vitamina C em Cápsulas',
    category: 'supplements',
    description: 'Vitamina C para fortalecimento do sistema imunológico e ação antioxidante.',
    price: 39.00,
    unit: 'un',
    image: getImage('vitamin-c-capsules'),
  },

  // Sucos e Bebidas (Adicionais - Total 16)
  {
    id: 'kombucha-cha-verde',
    name: 'Kombucha Chá Verde e Gengibre',
    category: 'juices',
    description: 'Bebida fermentada probiótica, sabor chá verde e gengibre, para saúde intestinal.',
    price: 14.50,
    unit: 'ml',
    image: getImage('kombucha-green-ginger'),
  },
  {
    id: 'cha-hibisco',
    name: 'Chá de Hibisco Pronto',
    category: 'juices',
    description: 'Chá de hibisco natural, diurético e antioxidante, pronto para beber.',
    price: 9.00,
    unit: 'ml',
    image: getImage('hibiscus-tea'),
  },
  {
    id: 'suco-beterraba-laranja',
    name: 'Suco de Beterraba e Laranja',
    category: 'juices',
    description: 'Suco natural de beterraba e laranja, excelente pré-treino e fonte de energia.',
    price: 16.00,
    unit: 'ml',
    image: getImage('beet-orange-juice'),
  },
  {
    id: 'leite-amendoas',
    name: 'Leite de Amêndoas Orgânico',
    category: 'juices',
    description: 'Bebida vegetal de amêndoas, sem lactose e sem glúten, enriquecida com cálcio.',
    price: 19.90,
    unit: 'l',
    image: getImage('almond-milk'),
  },
  {
    id: 'suco-uva-integral',
    name: 'Suco de Uva Integral Orgânico',
    category: 'juices',
    description: 'Suco de uva integral, sem adição de açúcar, rico em resveratrol.',
    price: 18.00,
    unit: 'l',
    image: getImage('grape-juice'),
  },
  {
    id: 'shot-imunidade',
    name: 'Shot de Imunidade Cúrcuma e Própolis',
    category: 'juices',
    description: 'Shot concentrado para fortalecer o sistema imunológico.',
    price: 13.50,
    unit: 'ml',
    image: getImage('immunity-shot'),
  },
  {
    id: 'cha-matcha',
    name: 'Matcha Latte Pronto',
    category: 'juices',
    description: 'Bebida refrescante à base de matcha, com leite vegetal e levemente adoçado.',
    price: 15.00,
    unit: 'ml',
    image: getImage('matcha-latte'),
  },
  {
    id: 'suco-melancia',
    name: 'Suco de Melancia Natural',
    category: 'juices',
    description: 'Suco de melancia natural, hidratante e refrescante.',
    price: 11.00,
    unit: 'ml',
    image: getImage('watermelon-juice'),
  },
  {
    id: 'agua-saborizada',
    name: 'Água Saborizada Limão e Hortelã',
    category: 'juices',
    description: 'Água mineral com infusão natural de limão e hortelã.',
    price: 8.00,
    unit: 'ml',
    image: getImage('flavored-water'),
  },
  {
    id: 'leite-coco',
    name: 'Leite de Coco em Garrafa',
    category: 'juices',
    description: 'Leite de coco fresco, ideal para receitas e bebidas.',
    price: 17.00,
    unit: 'ml',
    image: getImage('coconut-milk-bottle'),
  },

  // Castanhas e Oleaginosas (Adicionais - Total 16)
  {
    id: 'pistache',
    name: 'Pistache Torrado e Salgado',
    category: 'nuts',
    description: 'Pistache de alta qualidade, torrado e levemente salgado.',
    price: 55.00,
    unit: 'g',
    image: getImage('pistachios'),
  },
  {
    id: 'macadamia',
    name: 'Macadâmia Crua',
    category: 'nuts',
    description: 'Macadâmia crua, sabor delicado e textura amanteigada.',
    price: 65.00,
    unit: 'g',
    image: getImage('macadamia'),
  },
  {
    id: 'avelas',
    name: 'Avelãs Torradas',
    category: 'nuts',
    description: 'Avelãs torradas, perfeitas para doces e consumo in natura.',
    price: 48.00,
    unit: 'g',
    image: getImage('hazelnuts'),
  },
  {
    id: 'pinoli',
    name: 'Pinoli (Pinhão Europeu)',
    category: 'nuts',
    description: 'Pinoli, ingrediente essencial para pesto e culinária mediterrânea.',
    price: 85.00,
    unit: 'g',
    image: getImage('pine-nuts'),
  },
  {
    id: 'mix-castanhas',
    name: 'Mix de Castanhas Premium',
    category: 'nuts',
    description: 'Seleção de castanhas (caju, pará, amêndoas, nozes) para um lanche nutritivo.',
    price: 39.90,
    unit: 'g',
    image: getImage('premium-nut-mix'),
  },
  {
    id: 'amendoim-torrado',
    name: 'Amendoim Torrado sem Sal',
    category: 'nuts',
    description: 'Amendoim torrado e sem sal, fonte de energia e proteína.',
    price: 12.00,
    unit: 'kg',
    image: getImage('roasted-peanuts'),
  },
  {
    id: 'semente-abobora',
    name: 'Semente de Abóbora Torrada',
    category: 'nuts',
    description: 'Semente de abóbora torrada, rica em zinco e magnésio.',
    price: 25.00,
    unit: 'g',
    image: getImage('pumpkin-seeds'),
  },
  {
    id: 'castanha-baru',
    name: 'Castanha de Baru',
    category: 'nuts',
    description: 'Castanha de baru, nativa do cerrado, com alto valor nutricional.',
    price: 45.00,
    unit: 'g',
    image: getImage('baru-nuts'),
  },
  {
    id: 'amendoim-japones',
    name: 'Amendoim Japonês',
    category: 'nuts',
    description: 'Amendoim crocante com casquinha de farinha de trigo, saboroso e tradicional.',
    price: 15.00,
    unit: 'g',
    image: getImage('japanese-peanuts'),
  },
  {
    id: 'amendoas-defumadas',
    name: 'Amêndoas Defumadas',
    category: 'nuts',
    description: 'Amêndoas com um toque defumado, para um sabor diferenciado.',
    price: 32.00,
    unit: 'g',
    image: getImage('smoked-almonds'),
  },
  {
    id: 'castanha-caju-w1',
    name: 'Castanha de Caju W1 (Inteira)',
    category: 'nuts',
    description: 'Castanha de caju inteira (W1), a mais nobre e saborosa.',
    price: 38.00,
    unit: 'g',
    image: getImage('cashew-nuts-w1'),
  },
  {
    id: 'nozes-mariposa',
    name: 'Nozes Mariposa',
    category: 'nuts',
    description: 'Metades de nozes mariposa, ideais para confeitaria e decoração.',
    price: 40.00,
    unit: 'g',
    image: getImage('walnut-halves'),
  },

  // Óleos e Manteigas (Adicionais - Total 16)
  {
    id: 'oleo-abacate',
    name: 'Óleo de Abacate Extra Virgem',
    category: 'oils',
    description: 'Óleo de abacate prensado a frio, rico em gorduras monoinsaturadas, ideal para cocção em alta temperatura.',
    price: 55.00,
    unit: 'ml',
    image: getImage('avocado-oil'),
  },
  {
    id: 'oleo-gergelim',
    name: 'Óleo de Gergelim Torrado',
    category: 'oils',
    description: 'Óleo de gergelim torrado, essencial na culinária asiática, com sabor intenso.',
    price: 32.00,
    unit: 'ml',
    image: getImage('toasted-sesame-oil'),
  },
  {
    id: 'manteiga-amendoa',
    name: 'Manteiga de Amêndoa Integral',
    category: 'oils',
    description: 'Manteiga de amêndoa 100% integral, sem adição de açúcar ou óleos.',
    price: 45.00,
    unit: 'g',
    image: getImage('almond-butter'),
  },
  {
    id: 'oleo-linhaça',
    name: 'Óleo de Linhaça Dourada',
    category: 'oils',
    description: 'Óleo de linhaça prensado a frio, fonte de ômega 3, ideal para consumo cru.',
    price: 48.00,
    unit: 'ml',
    image: getImage('flaxseed-oil'),
  },
  {
    id: 'oleo-girassol',
    name: 'Óleo de Girassol Orgânico',
    category: 'oils',
    description: 'Óleo de girassol orgânico, suave e versátil para o dia a dia.',
    price: 25.00,
    unit: 'l',
    image: getImage('sunflower-oil'),
  },
  {
    id: 'manteiga-castanha-caju',
    name: 'Manteiga de Castanha de Caju',
    category: 'oils',
    description: 'Manteiga cremosa de castanha de caju, deliciosa e nutritiva.',
    price: 52.00,
    unit: 'g',
    image: getImage('cashew-butter'),
  },
  {
    id: 'azeite-trufa',
    name: 'Azeite de Oliva com Trufa Branca',
    category: 'oils',
    description: 'Azeite de oliva extra virgem com infusão de trufa branca, para pratos gourmet.',
    price: 75.00,
    unit: 'ml',
    image: getImage('truffle-oil'),
  },
  {
    id: 'oleo-ricino',
    name: 'Óleo de Rícino (Mamona)',
    category: 'oils',
    description: 'Óleo de rícino puro, para uso cosmético e medicinal.',
    price: 18.00,
    unit: 'ml',
    image: getImage('castor-oil'),
  },
  {
    id: 'oleo-pequi',
    name: 'Óleo de Pequi',
    category: 'oils',
    description: 'Óleo de pequi, sabor marcante, típico da culinária brasileira.',
    price: 30.00,
    unit: 'ml',
    image: getImage('pequi-oil'),
  },
  {
    id: 'manteiga-coco',
    name: 'Manteiga de Coco',
    category: 'oils',
    description: 'Manteiga de coco, alternativa vegana e saudável à manteiga tradicional.',
    price: 35.00,
    unit: 'g',
    image: getImage('coconut-butter'),
  },
  {
    id: 'oleo-alho',
    name: 'Óleo de Alho',
    category: 'oils',
    description: 'Óleo de alho em cápsulas, para saúde cardiovascular e imunidade.',
    price: 28.00,
    unit: 'un',
    image: getImage('garlic-oil-capsules'),
  },
  {
    id: 'oleo-oregano',
    name: 'Óleo de Orégano',
    category: 'oils',
    description: 'Óleo essencial de orégano, potente antifúngico e antibacteriano natural.',
    price: 60.00,
    unit: 'ml',
    image: getImage('oregano-oil'),
  },
  {
    id: 'oleo-palma',
    name: 'Óleo de Palma (Dendê)',
    category: 'oils',
    description: 'Óleo de palma (dendê), essencial na culinária baiana.',
    price: 15.00,
    unit: 'l',
    image: getImage('palm-oil'),
  },

  // Farinhas e Bases (Adicionais - Total 16)
  {
    id: 'farinha-trigo-integral',
    name: 'Farinha de Trigo Integral Orgânica',
    category: 'flours',
    description: 'Farinha de trigo integral orgânica, para pães e massas mais nutritivas.',
    price: 8.00,
    unit: 'kg',
    image: getImage('whole-wheat-flour'),
  },
  {
    id: 'polvilho-doce',
    name: 'Polvilho Doce',
    category: 'flours',
    description: 'Polvilho doce, ideal para biscoitos e pães de queijo.',
    price: 6.00,
    unit: 'kg',
    image: getImage('sweet-manioc-starch'),
  },
  {
    id: 'polvilho-azedo',
    name: 'Polvilho Azedo',
    category: 'flours',
    description: 'Polvilho azedo, para dar crocância e acidez em pães de queijo e tapiocas.',
    price: 6.50,
    unit: 'kg',
    image: getImage('sour-manioc-starch'),
  },
  {
    id: 'farinha-mandioca',
    name: 'Farinha de Mandioca Torrada',
    category: 'flours',
    description: 'Farinha de mandioca torrada, essencial para farofas e acompanhamentos.',
    price: 5.50,
    unit: 'kg',
    image: getImage('toasted-manioc-flour'),
  },
  {
    id: 'tapioca',
    name: 'Goma de Tapioca Hidratada',
    category: 'flours',
    description: 'Goma de tapioca hidratada, pronta para o preparo de tapiocas.',
    price: 7.50,
    unit: 'kg',
    image: getImage('tapioca-starch'),
  },
  {
    id: 'farinha-grao-bico',
    name: 'Farinha de Grão de Bico',
    category: 'flours',
    description: 'Farinha de grão de bico, rica em proteínas, para receitas sem glúten.',
    price: 18.00,
    unit: 'g',
    image: getImage('chickpea-flour'),
  },
  {
    id: 'farinha-banana-verde',
    name: 'Farinha de Banana Verde',
    category: 'flours',
    description: 'Farinha de banana verde, fonte de amido resistente, para saúde intestinal.',
    price: 15.00,
    unit: 'g',
    image: getImage('green-banana-flour'),
  },
  {
    id: 'farinha-linhaça',
    name: 'Farinha de Linhaça Dourada',
    category: 'flours',
    description: 'Farinha de linhaça dourada, moída na hora, rica em ômega 3.',
    price: 12.00,
    unit: 'g',
    image: getImage('flaxseed-flour'),
  },
  {
    id: 'farinha-arroz',
    name: 'Farinha de Arroz',
    category: 'flours',
    description: 'Farinha de arroz, alternativa sem glúten para espessar e cozinhar.',
    price: 9.00,
    unit: 'kg',
    image: getImage('rice-flour'),
  },
  {
    id: 'farinha-aveia-sem-gluten',
    name: 'Farinha de Aveia Sem Glúten',
    category: 'flours',
    description: 'Farinha de aveia certificada sem glúten, para celíacos e dietas restritivas.',
    price: 16.00,
    unit: 'g',
    image: getImage('gluten-free-oat-flour'),
  },
  {
    id: 'cacau-po',
    name: 'Cacau em Pó 100%',
    category: 'flours',
    description: 'Cacau em pó puro, sem açúcar, rico em antioxidantes.',
    price: 25.00,
    unit: 'g',
    image: getImage('cocoa-powder'),
  },
  {
    id: 'fermento-biologico',
    name: 'Fermento Biológico Seco',
    category: 'flours',
    description: 'Fermento biológico seco instantâneo, para pães e massas fermentadas.',
    price: 4.00,
    unit: 'un',
    image: getImage('dry-yeast'),
  },
  {
    id: 'acucar-coco',
    name: 'Açúcar de Coco Orgânico',
    category: 'flours',
    description: 'Açúcar de coco orgânico, com baixo índice glicêmico, alternativa saudável ao açúcar refinado.',
    price: 19.00,
    unit: 'g',
    image: getImage('coconut-sugar'),
  },
  {
    id: 'sal-rosa',
    name: 'Sal Rosa do Himalaia Fino',
    category: 'flours',
    description: 'Sal rosa do Himalaia fino, rico em minerais e com sabor suave.',
    price: 12.00,
    unit: 'kg',
    image: getImage('pink-himalayan-salt'),
  },
  {
    id: 'xilitol',
    name: 'Xilitol Adoçante Natural',
    category: 'flours',
    description: 'Xilitol, adoçante natural com baixo teor calórico.',
    price: 28.00,
    unit: 'g',
    image: getImage('xylitol'),
  },
  {
    id: 'eritritol',
    name: 'Eritritol Adoçante Natural',
    category: 'flours',
    description: 'Eritritol, adoçante natural sem calorias, ideal para dietas low-carb.',
    price: 32.00,
    unit: 'g',
    image: getImage('erythritol'),
  },
];

export const WHATSAPP_NUMBER = '5583987848625';
